# The URL the site will be built for
base_url = "https://crumplecup.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# theme
#theme = "after-dark"
theme = "blow"

taxonomies = [
	{name = "categories", feed = true},
	{name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Erik Rose"
after_dark_title = "Strange Inflections"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]

# config blow theme
[extra.lang]
items = [
    { lang = "en", links = [
        { base_url = "/", name = "English" },
    ] },
]

[extra.navbar]
items = [
    { lang = "en", links = [
        { url = "/", name = "Home" },
        { url = "/categories", name = "Articles" },
        { url = "/tags", name = "Subjects" },
	{ url = "/about/resume", name = "About Me" },
    ] },
]
title = "Strange Inflections"

[extra.sidebar]
items = [
    { lang = "en", links = [
        { url = "/categories", name = "Articles" },
        { url = "/tags", name = "Subjects" },
	{ url = "/about/resume", name = "About Me" },
    ] },
]

[extra.index]
title = "Strange Inflections"
image = "/knowles_df.jpg"

[extra.social]
email = "erik.w.rose@gmail.com"
gitlab = ""
github = "https://github.com/crumplecup"
linkedin = "https://www.linkedin.com/in/erik-rose-73749a26/"
twitter = "https://www.twitter.com/crumplecup"
facebook = "https://www.facebook.com/crumplecup"

[extra.default_author]
name = "Erik Rose"
avatar = "/avatar.png"
